x-veld:
  code:
    description: "A very simple curl call. Since many veld chains need to download data, it makes
      sense to encapsulate the download functionality into a dedicated downloader veld code"
    topic: ETL

    output:
      - volume: /veld/output/
        environment_var: out_file
        description: "optional. If unset, this script will fetch the file name from the resource."
        optional: true

    config:
      environment_var: url
      var_type: str
      description: "The url where some resource is located and should be downloaded from."

services:
  veld_downloader:
    build: .
    command: sh /veld/code/downloader.sh
    volumes: 
      - ./downloader.sh:/veld/code/downloader.sh
    environment:
      url: null
      out_file: null


